[[http://stable.melpa.org/#/grails-projectile-mode][file:http://stable.melpa.org/packages/grails-projectile-mode-badge.svg]] [[http://melpa.org/#/grails-projectile-mode][file:http://melpa.org/packages/grails-projectile-mode-badge.svg]]

* punctuality-logger

A simple punctuality logger for Emacs.

** Install

Get *punctuality-logger* from [[http://melpa.org][MELPA]].

To set-up MELPA, add the following code to =~/.emacs.d/init.el=.

#+begin_src elisp
(setq package-archives '(("gnu" . "http://elpa.gnu.org/packages/")
                         ("melpa" . "http://melpa.milkbox.net/packages/")))
#+end_src                         

Now, start Emacs and press =M-x package-install [RET] punctuality-logger=.

Now, add the following code to your emacs configuration file.

#+begin_src elisp
(require 'punctuality-logger)
#+end_src                         

** Use

Currently, *punctuality-logger* supports three interactive functions.

- *punctuality-logger-new-entry* asks you if you were late today and, if so, how many minutes you were late. It then creates a new log entry with your input.

- *punctuality-logger-late-days* lists in a new buffer the days you were late.

- *punctuality-logger-all-days* lists in a new buffer all the days in the log.

These functions are also available from the top-menu *Tools->Punctuality Logger*.
